set term=xterm-256color
set nocompatible

"buffer
set bufhidden=hide
set wildmenu
set wildignorecase
set updatetime=100 "For better performance in vim-githutter

"ctrlp
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_root_markers = ['package.json', "Cargo.toml"]

"encoding
scriptencoding utf-8
set encoding=utf-8

"line numbering
set number

"mouse support
set mouse=a
set ttymouse=xterm2

"statusline
set showcmd
set statusline=%m\ %f\ %=%4l/%L\ %P
set laststatus=2
set noruler

"colorscheme
let g:color_list=[['gruvbox', 'dark'], ['gruvbox', 'light'], ['smyck', 'dark']]
let g:color_current=-1
function! ChangeColorscheme()
	let g:color_current = (g:color_current + 1) % len(g:color_list)
	let c = g:color_list[g:color_current]
	execute('set background=' . c[1])
	execute('colorscheme ' . c[0])
endfunction
nnoremap <silent> <F3> :call ChangeColorscheme()<CR>
let g:gruvbox_italic=1

set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum
set t_Cs="\e[4:3m"
set t_Ce="\e[4:0m"
set termguicolors

set t_ut=
syntax enable
call ChangeColorscheme()

"show invisibles
set list listchars=tab:»·,trail:·,extends:·,precedes:·
highlight ExtraWhitespace guifg=purple
match ExtraWhitespace /\s\+$/
set nolist

"search settings
set ignorecase
set smartcase
set incsearch
set hlsearch

"windows split
set splitbelow
set splitright

"backspace
set backspace=indent,eol,start
set backspace=2

"===== Shortcuts =====
let mapleader=","
nnoremap <Leader>vr :so ~/.vimrc<CR>
nnoremap <Leader>vj :sp ~/.vimrc<CR>
nnoremap <Leader>vs :execute "sp ~/.vim/pack/my_settings/start/my_settings/syntax/".&ft.".vim"<CR>
nnoremap <Leader>n :NERDTreeToggle<CR>
nnoremap <Leader>/ /<C-R>"<cr>
nnoremap <Leader>a :w<CR>:make<CR>

"==== YouCompleteMe  ====
"let $RUSTFLAGS="$RUSTFLAGS -A dead_code" 
let g:ycm_python_binary_path = 'python'
let g:ycm_key_detailed_diagnostics = '<Leader>v'
let g:ycm_confirm_extra_conf = 0
let g:ycm_use_ultisnips_completer = 1
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_max_diagnostics_to_display = 10

let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

" GlobalFind
nnoremap <Leader>F "gyiw:Ggrep <C-r>g<CR>:copen
nnoremap <Leader>w :w !sudo tee "%" > /dev/null<cr>
iabbr shebang #!/usr/bin/env

au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
au BufNewFile,BufFilePre,BufRead *.jinja set filetype=jinja
au BufNewFile,BufFilePre,BufRead *.build set filetype=python
"indentation
filetype plugin indent on

" Compilation
" let g:program="echo No program set"
let g:arguments=""
nnoremap <F6> :let g:program=expand("%")
nnoremap <F7> :let g:arguments=
nnoremap <F8> :execute(":!clear && " . g:program . " " . g:arguments)<CR>


